<?php
include ("Connect.php"); 
// sql to create table
$sql = "CREATE TABLE IF NOT EXISTS SHEET1 (
RID INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
PART_NO VARCHAR(255) NOT NULL,
PARTI VARCHAR(255) NOT NULL,
MRP VARCHAR(255),
GROP VARCHAR(255),
CATE VARCHAR(255),
DPCODE VARCHAR(255),
lmodi VARCHAR(255),
TRATE VARCHAR(255),
RID1 VARCHAR(255),
UNIT VARCHAR(255),
AEDT VARCHAR(255)
)";

$sql1 = "CREATE TABLE IF NOT EXISTS TABLE1 (
RID1 INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
TYPE VARCHAR(255), 
PART_NO VARCHAR(255) NOT NULL,
PARTI VARCHAR(255) NOT NULL,
MRP VARCHAR(255),
QTY VARCHAR(255),
TOTAL VARCHAR(255),
RACKNO VARCHAR(255),
TAX VARCHAR(255),
TVAL VARCHAR(255),
STOTAL VARCHAR(255),
PPRICE VARCHAR(255),
SPRICE VARCHAR(255),
SSTA VARCHAR(255),
EOR VARCHAR(255),
GROP VARCHAR(255),
DPCODE VARCHAR(255),
lmodi VARCHAR(255),
RID VARCHAR(255),
UNIT VARCHAR(255),
AEDT VARCHAR(255),
USER1 VARCHAR(255)
)";


if (mysqli_query($db1, $sql)) {
} else {
    echo "Error creating table: " . mysqli_error($db1);
}

if (mysqli_query($db1, $sql1)) {
} else {
    echo "Error creating table: " . mysqli_error($db1);
}

mysqli_close($db1);
?>