'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DB1Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DB1Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property BILL() As DbSet(Of BILL)
    Public Overridable Property BILL1() As DbSet(Of BILL1)
    Public Overridable Property CUST() As DbSet(Of CUST)
    Public Overridable Property CUSTOMER() As DbSet(Of CUSTOMER)
    Public Overridable Property MAINPOPU() As DbSet(Of MAINPOPU)
    Public Overridable Property PMR() As DbSet(Of PMR)
    Public Overridable Property PURCHSE() As DbSet(Of PURCHSE)
    Public Overridable Property PURCHSE1() As DbSet(Of PURCHSE1)
    Public Overridable Property SHEET1() As DbSet(Of SHEET1)
    Public Overridable Property TABLE1() As DbSet(Of TABLE1)
    Public Overridable Property user1() As DbSet(Of user1)

End Class
