'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PMR
    Public Property RECID1 As Integer
    Public Property SID As String
    Public Property SNAME As String
    Public Property ENGINE_No As String
    Public Property DOS As Nullable(Of Date)
    Public Property STYPE As String
    Public Property HMR As String
    Public Property Report As String
    Public Property Technician As String
    Public Property METERIAL As String
    Public Property CUST As String
    Public Property recid As String
    Public Property CDATI As Nullable(Of Date)
    Public Property DIST As String
    Public Property STATE As String
    Public Property CCATE As String
    Public Property MODEL As String
    Public Property DOI As Nullable(Of Date)
    Public Property DGNO As String
    Public Property AMAKE As String
    Public Property ALSN As String
    Public Property BSN As String
    Public Property CNAT As String
    Public Property SERV As String
    Public Property RFAIL As String
    Public Property STA As String
    Public Property WARR As String
    Public Property ACTION As String
    Public Property OEA As String
    Public Property AMC As String
    Public Property TTR As String
    Public Property SLA As String
    Public Property TSLOT As String
    Public Property RESLA As String
    Public Property KVA As String
    Public Property SSTA As String
    Public Property DPCODE As String
    Public Property lmodi As String
    Public Property AEDT As String

End Class
